
#define GLM_FORCE_RADIANS
#define GLM_FORCE_DEPTH_ZERO_TO_ONE
#include <glm/glm.hpp>
#include <glm/gtc/constants.hpp>

#include "simple_rendersys.hpp"
#include "handy_mats.h"

#include <stdexcept>
#include <array>
#include <iostream>
namespace vke {

	struct SimplePushConstantData {
		glm::mat4 world_transform = rotateMatX(glm::quarter_pi<float>());		// world transform push constant mat - init to identiy
		//alignas(32) glm::mat2 transform{ 1.f };
		//alignas(16) glm::vec2 offset;
		//alignas(16) glm::vec3 color;		// ADDED TO FIX PUSH CONSTANT ALIGNMENT
	};
	
	// Constructor Imp.
	// - pulls in device, renderpass, and descriptor layout (from renderer)
	SimpleRenderSys::SimpleRenderSys(VkDerkDevice& device, VkRenderPass renderPass, VkDescriptorSetLayout descSetLayout) 
		: vkDerkDevice{ device }, descriptorSetLayoutRef{ descSetLayout } {

		createPipelineLayout();
		createPipeline(renderPass);
	}

	// Destructor Imp.
	SimpleRenderSys::~SimpleRenderSys() {
		vkDestroyPipelineLayout(vkDerkDevice.device(), pipelineLayout, nullptr);
		//createPipeline();
	}

	// CREATE PIPELINE LAYOUT
	void SimpleRenderSys::createPipelineLayout() {

		// Push constant range
		VkPushConstantRange pushConstantRange{};
		pushConstantRange.stageFlags = VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT;	// signals that we want push constant data in both vertex and fragment shaders!
		pushConstantRange.offset = 0;
		pushConstantRange.size = sizeof(SimplePushConstantData);

		VkPipelineLayoutCreateInfo pipelineLayoutInfo{};
		pipelineLayoutInfo.sType = VK_STRUCTURE_TYPE_PIPELINE_LAYOUT_CREATE_INFO;
		pipelineLayoutInfo.setLayoutCount = 1;											// updated for uniform buffer descriptor set
		pipelineLayoutInfo.pSetLayouts = &descriptorSetLayoutRef;						// uses descriptor set generated by renderer and pulled in thru constructor
		pipelineLayoutInfo.pushConstantRangeCount = 1;
		pipelineLayoutInfo.pPushConstantRanges = &pushConstantRange;

		if (vkCreatePipelineLayout(vkDerkDevice.device(), &pipelineLayoutInfo, nullptr, &pipelineLayout) != VK_SUCCESS) {
			throw std::runtime_error("failed to create pipeline layout!");
		}
	}

	// CREATE GRAPHICS PIPELINE 
	void SimpleRenderSys::createPipeline(VkRenderPass renderPass) {
		assert(pipelineLayout != nullptr && "Cannot create pipeline before pipeline layout!");


		PipelineConfigInfo pipelineConfig{};
		VkePipeline::defaultPipelineConfigInfo(pipelineConfig);

		pipelineConfig.renderPass = renderPass;
		pipelineConfig.pipelineLayout = pipelineLayout;
		vkePipeline = std::make_unique<VkePipeline>(
			vkDerkDevice,
			"simple_shader.vert.spv",
			"simple_shader.frag.spv",
			pipelineConfig);
	}

	//void SimpleRenderSys::renderGameObjects(VkCommandBuffer commandBuffer, std::vector<VkeGameObject> &gameObjects, VkDescriptorSet descSet) {
	void SimpleRenderSys::renderGameObjects(VkCommandBuffer commandBuffer, std::vector<VkeGameObject>& gameObjects, VkDescriptorSet descSet) {
		// Cool Triangle Animations - push constants
		/*
		int i = 0;
		for (auto& obj : gameObjects) {
			i += 1;
			obj.transform2d.rotation = glm::mod<float>(obj.transform2d.rotation + 0.001f * i, 2.f * glm::pi<float>());
			//obj.transform2d.translation.x = glm::sin(glm::pi<float>() / i);
			obj.transform2d.translation.x = glm::mod<float>(obj.transform2d.translation.x + 0.002f * i, 2.f * glm::pi<float>());
		}
		*/
		//world_theta += glm::two_pi<float>() / 2880.f;


		vkePipeline->bind(commandBuffer);

		// bind descriptor sets to buffs
		vkCmdBindDescriptorSets(commandBuffer, VK_PIPELINE_BIND_POINT_GRAPHICS, pipelineLayout, 0, 1, &descSet, 0, nullptr);

		for (auto& obj : gameObjects) {
			//obj.transform2d.rotation = glm::mod(obj.transform2d.rotation + 0.001f, glm::two_pi<float>());		// make the game objs rotate!!!

			// Push constants
			
			SimplePushConstantData push{};
			push.world_transform = rotateMatX(world_theta);
			
			//push.offset = obj.transform2d.translation;
			//push.color = obj.color;
			//push.transform = obj.transform2d.mat2();

			vkCmdPushConstants(
				commandBuffer,
				pipelineLayout,
				VK_SHADER_STAGE_VERTEX_BIT | VK_SHADER_STAGE_FRAGMENT_BIT,
				0,
				sizeof(SimplePushConstantData),
				&push);
			

			obj.model->bind(commandBuffer);
			obj.model->draw(commandBuffer);
		}

	}

}